#ifdef REALCASE
#undef DOUBLE_PRECISION_REAL
#undef SINGLE_PRECSION_REAL
#undef  MATH_DATATYPE
#undef  BLAS_TRANS_OR_CONJ
#undef  BLAS_CHAR
#undef  BLAS_CHAR_AND_SY_OR_HE
#undef  PRECISION
#undef  SPECIAL_COMPLEX_DATATYPE
#undef  PRECISION_STR
#undef  REAL_DATATYPE
#undef  C_REAL_DATATYPE

#undef  PRECISION_TRTRI
#undef  PRECISION_POTRF
#undef  PRECISION_TRSM
#undef  PRECISION_GEMV
#undef  PRECISION_TRMV
#undef  PRECISION_GEMM
#undef  PRECISION_TRMM
#undef  PRECISION_HERK
#undef  PRECISION_SYRK
#undef  PRECISION_SYMV
#undef  PRECISION_SYMM
#undef  PRECISION_HEMV
#undef  PRECISION_HER2
#undef  PRECISION_SYR2
#undef  PRECISION_SYR2K
#undef  PRECISION_GEQRF
#undef  PRECISION_STEDC
#undef  PRECISION_STEQR
#undef  PRECISION_LAMRG
#undef  PRECISION_LAMCH
#undef  PRECISION_LAPY2
#undef  PRECISION_LAED4
#undef  PRECISION_LAED5
#undef  PRECISION_NRM2
#undef  PRECISION_LASET
#undef  cublas_PRECISION_GEMM
#undef  cublas_PRECISION_TRMM
#undef  cublas_PRECISION_GEMV
#undef  cublas_PRECISION_SYMV
#undef  scal_PRECISION_GEMM
#undef  scal_PRECISION_NRM2
#undef  scal_PRECISION_LASET
#undef  PRECISION_SUFFIX
#undef  ELPA_IMPL_SUFFIX

#undef  MPI_REAL_PRECISION
#undef  MPI_MATH_DATATYPE_PRECISION
#undef  MPI_MATH_DATATYPE_PRECISION_EXPL
#undef  C_DATATYPE_KIND
#undef THRESHOLD


/* General definitions needed in single and double case */
#define  MATH_DATATYPE real
#define  BLAS_TRANS_OR_CONJ 'T'

#ifdef DOUBLE_PRECISION
#define DOUBLE_PRECISION_REAL
#define  PRECISION double
#define  PRECISION_STR 'double'
#define  PRECISION_SUFFIX "_double"
#define  ELPA_IMPL_SUFFIX d
#define  REAL_DATATYPE rk8
#define  C_REAL_DATATYPE c_double
#define  BLAS_CHAR D
#define BLAS_CHAR_AND_SY_OR_HE DSY
#define  SPECIAL_COMPLEX_DATATYPE ck8

#define  PRECISION_TRTRI DTRTRI
#define  PRECISION_POTRF DPOTRF
#define  PRECISION_TRSM DTRSM
#define  PRECISION_GEMV DGEMV
#define  PRECISION_TRMV DTRMV
#define  PRECISION_GEMM DGEMM
#define  PRECISION_TRMM DTRMM
#define  PRECISION_HERK DHERK
#define  PRECISION_SYRK DSYRK
#define  PRECISION_SYMV DSYMV
#define  PRECISION_SYMM DSYMM
#define  PRECISION_HEMV DHEMV
#define  PRECISION_HER2 DHER2
#define  PRECISION_SYR2 DSYR2
#define  PRECISION_SYR2K DSYR2K
#define  PRECISION_GEQRF DGEQRF
#define  PRECISION_STEDC DSTEDC
#define  PRECISION_STEQR DSTEQR
#define  PRECISION_LAMRG DLAMRG
#define  PRECISION_LAMCH DLAMCH
#define  PRECISION_LAPY2 DLAPY2
#define  PRECISION_LAED4 DLAED4
#define  PRECISION_LAED5 DLAED5
#define  PRECISION_NRM2 DNRM2
#define  PRECISION_LASET DLASET
#define  cublas_PRECISION_GEMM cublas_DGEMM
#define  cublas_PRECISION_TRMM cublas_DTRMM
#define  cublas_PRECISION_GEMV cublas_DGEMV
#define  cublas_PRECISION_SYMV cublas_DSYMV
#define  scal_PRECISION_GEMM PDGEMM
#define  scal_PRECISION_NRM2 PDNRM2
#define  scal_PRECISION_LASET PDLASET
#define  MPI_REAL_PRECISION MPI_REAL8
#define  MPI_MATH_DATATYPE_PRECISION MPI_REAL8
#define  MPI_MATH_DATATYPE_PRECISION_EXPL MPI_REAL8
#define  C_DATATYPE_KIND c_double

#define THRESHOLD 1e-11_rk8
#endif /* DOUBLE_PRECISION */

#ifdef SINGLE_PRECISION

#define SINGLE_PRECISION_REAL

#define  PRECISION single
#define  PRECISION_STR 'single'
#define  PRECISION_SUFFIX "_single"
#define  ELPA_IMPL_SUFFIX f
#define  REAL_DATATYPE rk4
#define  C_REAL_DATATYPE c_float
#define  BLAS_CHAR S
#define  BLAS_CHAR_AND_SY_OR_HE SSY
#define  SPECIAL_COMPLEX_DATATYPE ck4

#define  PRECISION_TRTRI STRTRI
#define  PRECISION_POTRF SPOTRF
#define  PRECISION_TRSM STRSM
#define  PRECISION_GEMV SGEMV
#define  PRECISION_TRMV STRMV
#define  PRECISION_GEMM SGEMM
#define  PRECISION_TRMM STRMM
#define  PRECISION_HERK SHERK
#define  PRECISION_SYRK SSYRK
#define  PRECISION_SYMV SSYMV
#define  PRECISION_SYMM SSYMM
#define  PRECISION_HEMV SHEMV
#define  PRECISION_HER2 SHER2
#define  PRECISION_SYR2 SSYR2
#define  PRECISION_SYR2K SSYR2K
#define  PRECISION_GEQRF SGEQRF
#define  PRECISION_STEDC SSTEDC
#define  PRECISION_STEQR SSTEQR
#define  PRECISION_LAMRG SLAMRG
#define  PRECISION_LAMCH SLAMCH
#define  PRECISION_LAPY2 SLAPY2
#define  PRECISION_LAED4 SLAED4
#define  PRECISION_LAED5 SLAED5
#define  PRECISION_NRM2 SNRM2
#define  PRECISION_LASET SLASET
#define  cublas_PRECISION_GEMM cublas_SGEMM
#define  cublas_PRECISION_TRMM cublas_STRMM
#define  cublas_PRECISION_GEMV cublas_SGEMV
#define  cublas_PRECISION_SYMV cublas_SSYMV
#define  scal_PRECISION_GEMM PSGEMM
#define  scal_PRECISION_NRM2 PSNRM2
#define  scal_PRECISION_LASET PSLASET
#define  MPI_REAL_PRECISION MPI_REAL4
#define  MPI_MATH_DATATYPE_PRECISION MPI_REAL4
#define  MPI_MATH_DATATYPE_PRECISION_EXPL MPI_REAL4
#define  C_DATATYPE_KIND c_float

#define THRESHOLD 1e-4_rk4
#endif /* SINGLE_PRECISION */

#endif /* REALCASE */

#ifdef COMPLEXCASE

#undef DOUBLE_PRECISION_COMPLEX
#undef SINGLE_PRECISION_COMPLEX
#undef  MATH_DATATYPE
#undef  BLAS_TRANS_OR_CONJ
#undef  BLAS_CHAR
#undef  BLAS_CHAR_AND_SY_OR_HE
#undef  PRECISION
#undef COMPLEX_DATATYPE
/* in the complex case also sometime real valued variables are needed */
#undef REAL_DATATYPE
#undef C_REAL_DATATYPE

#undef  PRECISION_TRTRI
#undef  PRECISION_POTRF
#undef  PRECISION_TRSM
#undef  PRECISION_STR
#undef  PRECISION_GEMV
#undef  PRECISION_TRMV
#undef  PRECISION_GEMM
#undef  PRECISION_TRMM
#undef  PRECISION_HERK
#undef  PRECISION_SYRK
#undef  PRECISION_SYMV
#undef  PRECISION_SYMM
#undef  PRECISION_HEMV
#undef  PRECISION_HER2
#undef  PRECISION_SYR2
#undef  PRECISION_SYR2K
#undef  PRECISION_GEQRF
#undef  PRECISION_STEDC
#undef  PRECISION_STEQR
#undef  PRECISION_LAMRG
#undef  PRECISION_LAMCH
#undef  PRECISION_LAPY2
#undef  PRECISION_LAED4
#undef  PRECISION_LAED5
#undef  PRECISION_DOTC
#undef  PRECISION_LASET
#undef  cublas_PRECISION_GEMM
#undef  cublas_PRECISION_TRMM
#undef  cublas_PRECISION_GEMV
#undef  cublas_PRECISION_SYMV
#undef  scal_PRECISION_GEMM
#undef  scal_PRECISION_DOTC
#undef  scal_PRECISION_LASET
#undef  PRECISION_SUFFIX
#undef  ELPA_IMPL_SUFFIX
#undef  MPI_COMPLEX_PRECISION
#undef  MPI_MATH_DATATYPE_PRECISION
#undef  MPI_MATH_DATATYPE_PRECISION_EXPL
#undef  MPI_COMPLEX_EXPLICIT_PRECISION
#undef  MPI_REAL_PRECISION
#undef  KIND_PRECISION
#undef  PRECISION_CMPLX
#undef  PRECISION_IMAG
#undef  PRECISION_REAL
#undef  C_DATATYPE_KIND


#undef THRESHOLD

/* General definitions needed in single and double case */
#define  MATH_DATATYPE complex
#define  BLAS_TRANS_OR_CONJ 'C'
#ifdef DOUBLE_PRECISION

#define DOUBLE_PRECISION_COMPLEX
#define  PRECISION double
#define  PRECISION_STR 'double'
#define  PRECISION_SUFFIX "_double"
#define  ELPA_IMPL_SUFFIX dc
#define COMPLEX_DATATYPE CK8
#define BLAS_CHAR Z
#define BLAS_CHAR_AND_SY_OR_HE ZHE
#define REAL_DATATYPE RK8
#define C_REAL_DATATYPE c_double

#define  PRECISION_TRTRI ZTRTRI
#define  PRECISION_POTRF ZPOTRF
#define  PRECISION_TRSM ZTRSM
#define  PRECISION_GEMV ZGEMV
#define  PRECISION_TRMV ZTRMV
#define  PRECISION_GEMM ZGEMM
#define  PRECISION_TRMM ZTRMM
#define  PRECISION_HERK ZHERK
#define  PRECISION_SYRK ZSYRK
#define  PRECISION_SYMV ZSYMV
#define  PRECISION_SYMM ZSYMM
#define  PRECISION_HEMV ZHEMV
#define  PRECISION_HER2 ZHER2
#define  PRECISION_SYR2 ZSYR2
#define  PRECISION_SYR2K ZSYR2K
#define  PRECISION_GEQRF ZGEQRF
#define  PRECISION_STEDC ZSTEDC
#define  PRECISION_STEQR ZSTEQR
#define  PRECISION_LAMRG ZLAMRG
#define  PRECISION_LAMCH ZLAMCH
#define  PRECISION_LAPY2 ZLAPY2
#define  PRECISION_LAED4 ZLAED4
#define  PRECISION_LAED5 ZLAED5
#define  PRECISION_DOTC ZDOTC
#define  PRECISION_LASET ZLASET
#define  cublas_PRECISION_GEMM cublas_ZGEMM
#define  cublas_PRECISION_TRMM cublas_ZTRMM
#define  cublas_PRECISION_GEMV cublas_ZGEMV
#define  cublas_PRECISION_SYMV cublas_ZSYMV
#define  scal_PRECISION_GEMM PZGEMM
#define  scal_PRECISION_DOTC PZDOTC
#define  scal_PRECISION_LASET PZLASET
#define  MPI_COMPLEX_PRECISION MPI_DOUBLE_COMPLEX
#define  MPI_MATH_DATATYPE_PRECISION MPI_DOUBLE_COMPLEX
#define  MPI_MATH_DATATYPE_PRECISION_EXPL MPI_COMPLEX16
#define  MPI_COMPLEX_EXPLICIT_PRECISION MPI_COMPLEX16
#define  MPI_REAL_PRECISION MPI_REAL8
#define  KIND_PRECISION rk8
#define  PRECISION_CMPLX DCMPLX
#define  PRECISION_IMAG DIMAG
#define  PRECISION_REAL DREAL
#define  C_DATATYPE_KIND c_double

#define THRESHOLD 1e-11_rk8
#endif /* DOUBLE PRECISION */

#ifdef SINGLE_PRECISION
#define SINGLE_PRECISION_COMPLEX
#define  PRECISION single
#define  PRECISION_STR 'single'
#define  PRECISION_SUFFIX "_single"
#define  ELPA_IMPL_SUFFIX fc
#define COMPLEX_DATATYPE CK4
#define BLAS_CHAR C
#define BLAS_CHAR_AND_SY_OR_HE CHE
#define REAL_DATATYPE RK4
#define C_REAL_DATATYPE c_float

#define  PRECISION_TRTRI CTRTRI
#define  PRECISION_POTRF CPOTRF
#define  PRECISION_TRSM CTRSM
#define  PRECISION_GEMV CGEMV
#define  PRECISION_TRMV CTRMV
#define  PRECISION_GEMM CGEMM
#define  PRECISION_TRMM CTRMM
#define  PRECISION_HERK CHERK
#define  PRECISION_SYRK CSYRK
#define  PRECISION_SYMV CSYMV
#define  PRECISION_SYMM CSYMM
#define  PRECISION_HEMV CHEMV
#define  PRECISION_HER2 CHER2
#define  PRECISION_SYR2 CSYR2
#define  PRECISION_SYR2K CSYR2K
#define  PRECISION_GEQRF CGEQRF
#define  PRECISION_STEDC CSTEDC
#define  PRECISION_STEQR CSTEQR
#define  PRECISION_LAMRG CLAMRG
#define  PRECISION_LAMCH CLAMCH
#define  PRECISION_LAPY2 CLAPY2
#define  PRECISION_LAED4 CLAED4
#define  PRECISION_LAED5 CLAED5
#define  PRECISION_DOTC CDOTC
#define  PRECISION_LASET CLASET
#define  cublas_PRECISION_GEMM cublas_CGEMM
#define  cublas_PRECISION_TRMM cublas_CTRMM
#define  cublas_PRECISION_GEMV cublas_CGEMV
#define  cublas_PRECISION_SYMV cublas_CSYMV
#define  scal_PRECISION_GEMM PCGEMM
#define  scal_PRECISION_DOTC PCDOTC
#define  scal_PRECISION_LASET PCLASET
#define  MPI_COMPLEX_PRECISION MPI_COMPLEX
#define  MPI_MATH_DATATYPE_PRECISION MPI_COMPLEX
#define  MPI_MATH_DATATYPE_PRECISION_EXPL MPI_COMPLEX8
#define  MPI_COMPLEX_EXPLICIT_PRECISION MPI_COMPLEX8
#define  MPI_REAL_PRECISION MPI_REAL4
#define  KIND_PRECISION rk4
#define  PRECISION_CMPLX CMPLX
#define  PRECISION_IMAG AIMAG
#define  PRECISION_REAL REAL
#define  C_DATATYPE_KIND c_float

#define THRESHOLD 1e-4_rk4
#endif /* SINGLE PRECISION */

#endif /* COMPLEXCASE */
